### ISSUE TITLE
Why is there a problem with the build release, and the debug version is fine?

### ISSUE THREAD

**Issue by kuangjiu** [APISENSE/rhino-android#8]
hi，can you help me ?

The release version uses the proguard as follows：
proguard.cfg：
##javascript io.apisense:rhino-android
-keep class javax.script.** { *; }
-keep class com.sun.script.javascript.** { *; }
-keep class org.mozilla.javascript.** { *; }
-dontwarn org.mozilla.javascript.**
-dontwarn sun.**

build.gradle：
  Release {
             minifyEnabled true
             proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard.cfg'
         }

 Config.log("engine rhino:" + new ScriptEngineManager().getEngineByName("rhino"));
        Config.log("engine js:" + new ScriptEngineManager().getEngineByName("js"));
        Config.log("engine JS:" + new ScriptEngineManager().getEngineByName("JS"));
        Config.log("engine JavaScript:" + new ScriptEngineManager().getEngineByName("JavaScript"));
        Config.log("engine javascript:" + new ScriptEngineManager().getEngineByName("javascript"));
result：
System.out: engine rhino:null
System.out: engine js:null
System.out: engine JS:null
System.out: engine JavaScript:null
System.out: engine javascript:null

when minifyEnabled is false,the running ok。

thank you very much.

**Comment by aveuiller** [comment]
Hello,
First of all, thanks for using this project.

There seems to be a problem indeed with the proguard minification configuration, I could reproduce your bug on both android 21 and 29. I have no quick solution at the moment, I guess it's related to an update of proguard or the build tools.
You can try it out with this sample project: https://github.com/aveuiller/RhinoSampleApp

I will try to dig this and see it that's related to an update of proguard or the build tools.
I will update the sample project and come back to you if I find a solution.

Don't hesitate to do the same if you find the missing configuration :)

**Comment by kuangjiu** [comment]
thank you for your reply

When I compile minifyEnabled == false, immediately change minifyEnabled = true, the program runs without problems (too fast, whether some files have not been updated yet), can provide a solution?

**Comment by kuangjiu** [comment]
https://github.com/aveuiller/RhinoSampleApp

This project has the same problem

MainActivity: Fetching ScriptEngine for label 'rhino' (success: false)
MainActivity: Fetching ScriptEngine for label 'js' (success: false)
MainActivity: Fetching ScriptEngine for label 'JS' (success: false)
MainActivity: Fetching ScriptEngine for label 'JavaScript' (success: false)
MainActivity: Fetching ScriptEngine for label 'javascript' (success: false)

**Comment by aveuiller** [comment]
Hello,

It seems that Androind is switching from Proguard to R8 to shrink the applications. You can find an interesting article on the subject on GuardSquare: https://www.guardsquare.com/en/blog/proguard-and-r8

It seems that the proguard configuration we use for rhino is not compatible (or not used) with R8, thus the sun classes are removed from the final apk.

I fixed the sample app to force the use of proguard, and as yo can see it works again.

Here is the interesting line added to the `gradle.properties`: https://github.com/aveuiller/RhinoSampleApp/blob/master/gradle.properties#L16

If you find a way to make the configuration work on R8, do not hesitate to notify me. I would gladly document the use in details in this project.

**Comment by Akshay-WL** [comment]
I still have this problem. 
Adding `android.enableR8=false` in `gradle.properties ` not solved problem.

For more info, In my progaurd I have added below lines

```
#Mozila Rhino
-dontwarn org.mozilla.javascript.**
-keep class org.mozilla.javascript.** { *; }
-keep class javax.script.** { *; }
-keep class com.sun.script.javascript.** { *; }
-keep class org.mozilla.javascript.* { ; }
```

**Comment by aveuiller** [comment]
Hello,

What is not working exactly? I had to make a few adjustements to your Proguard configuration since the one you provided did not compile.

The sample project did work with the following configuration, both in `debug` and `release`:
```
#Mozila Rhino
-dontwarn sun.**
-dontwarn org.mozilla.javascript.**
-keep class org.mozilla.javascript.** { *; }
-keep class javax.script.** { *; }
-keep class com.sun.script.javascript.** { *; }
-keep class org.mozilla.javascript.* { *; }
```

Do you have more info about your issue?

**Comment by Akshay-WL** [comment]
Ok first thank your reply.
My problem has been solved.
I have to call java functions from javascript, so I created one class that act as interface between rhino and java.
I have to add my class in `proguard`. 

like 
`-keep class com.mypackage.classname { *; }`
Note: This is dummy package and classname.

**Comment by aveuiller** [comment]
Happy to hear that!

I'm closing the issue then. Don't hesitate to open a new one if you have another issue :)

**Comment by e4basil** [comment]
any permanent solution for this issue ?

**Comment by kuangjiu** [comment]
It seems that the new version of android studio or Gradle has fixed this problem?

**Comment by aveuiller** [comment]
You are right @kuangjiu, the latest versions seems to fix the issue.

 I could reproduce the same behaviour between Proguard and R8 by mainly updating the Android SDK. You can find the changelog on this PR: https://github.com/aveuiller/RhinoSampleApp/pull/1/files

**Comment by kuangjiu** [comment]
@aveuiller ，Thank you for your contribution.

**Comment by hussamDana92** [comment]
any solution for this issue ?
